### ISSUE TITLE
Failed to find the azure spatial anchor (HoloLens 2)

### ISSUE THREAD

**Issue by echoxr** [TakahiroMiyaura/WayFindingSamplesUsingASA#8]
Thank you very much for your great work！

HoloLens 2の実機で動かしてみましたが、
2回目以降の起動で、「Find Azure Anchor」のボタンを押して、アンカー取得が動かないです。
ご確認いただけると助かります。

![20210316_173321_HoloLens](https://user-images.githubusercontent.com/80943634/111744604-d13cdf00-88ce-11eb-99b6-c24a5ddae24c.jpg)

- PC
>  Windows 10 Pro 2004
- HoloLens 2
- Unity 2019.4.17f1
- Visual Studio 2019 (16.8.6)
- Azure Spatial anchors 2.2.0
- Mixed Reality Toolkit 2.3.0
- AR Foundation 2.1.10

**Comment by TakahiroMiyaura** [comment]
Hi echoxr,

Thank you!

When you try to find the first anchors, are there any errors? or you can't find it very very long time?
I guess that Azure Spatial Anchors can't be found the spatial anchors, and if that's right, this status isn't bug.
if you can do it, please confirm the below:

* When the application is the search process, you gaze the space in the vicinity of placed spatial anchors.
* If there are no error, please check your spaces that you tried this application.  the space is important so that Azure Spatial Anchors is work good. This will affect success rate.
  https://docs.microsoft.com/en-US/azure/spatial-anchors/concepts/guidelines-effective-anchor-experiences

Best regards,

**Comment by TakahiroMiyaura** [comment]
This issue may be Azure Spatial Anchors SDK version. 
This sample code is supported ASA 2.2.1, but I must upgrade this project to ASA version 2.7.0 SDK or later.
The reason for this mandatory upgrade is that Azure Spatial Anchors service is being impacted by the move away from Baltimore CyberTrust Root CA (https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.7.0).

Fixed this problem in  #9.
